---
title: "STAT253"
author: "Federico Chung, KY, Niketh Gamage, Josh Upadhyay"
date: "10/3/2019"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)  # for plots
library(dplyr)    # for wrangling
library(caret)    # for machine learning algorithms
library(tidyr)    # because
library(naniar)   # we need it 
```


```{r}
data<- read.csv("airbnb_joined.csv")

```

```{r}
set.seed(256)

data<-data%>%
  sample_n(5000)

data

data<- data %>% filter(price<1000)

```


```{r}
names(data)
na_strings <- c("NA", "N A", "N / A", "N/A", "N/ A", "Not Available", "NOt available")

data<-data%>%
  replace_with_na_all(condition = ~.x %in% na_strings)
data <- data %>%
  mutate(bathrooms2 = replace_na(bathrooms, mean(bathrooms, na.rm = TRUE)))%>%
  mutate(beds2 = replace_na(beds, mean(beds, na.rm = TRUE)))%>%
  mutate(reviews2 = replace_na(reviews_per_month, mean(reviews_per_month, na.rm = TRUE)))%>%
  mutate(host_response_rate2 = replace_na(host_response_rate, mean(host_response_rate, na.rm = TRUE)))
```


```{r}
data_small<- data%>% select(-c(id, is_location_exact, calendar_updated, latitude, longitude, square_feet))
sum(complete.cases(data_small))

colSums(is.na(data))

```

```{r}
data_small<- data%>% select(-c(id, is_location_exact, calendar_updated, latitude, longitude, square_feet))
sum(complete.cases(data_small))

colSums(is.na(data))

colSums(is.na(data_small))

```


```{r}
colSums(is.na(data))


data_small<- data%>% select(-c(X,id, is_location_exact, calendar_updated, latitude, longitude, square_feet))

```



```{r}
impute_info <- data_small %>%
  preProcess(method = "knnImpute")
data_complete <- predict(impute_info, newdata = data_small) 

```

```{r}
colSums(is.na(data_complete))
sum(complete.cases(data_complete))
```

##Part 2: Analyze
##Narrowing down predictors:LASSO
    ```{r}
    # Define a range of lambda tuning parameters to try
    lambda_grid <- 10^seq(-3, 0.5, length = 100)

    # Set the seed
    set.seed(253)

    # Perform LASSO
    lasso_model_data <- train(
      price~.,
      data = data_complete,
      method = "glmnet",
      trControl = trainControl(method = "cv", number = 10, selectionFunction = "best"),
      tuneGrid = data.frame(alpha=1, lambda=lambda_grid),
      metric = "MAE",
      na.action = na.omit
    )
    ```
    
    ```{r}
    # Plot coefficients for each LASSO
    plot(lasso_model_data$finalModel, xvar = "lambda", label = TRUE, col = rainbow(20))
    # Codebook for which variables the numbers correspond to
    rownames(lasso_model_data$finalModel$beta)
    ```   
    ```{r}
    # Plot metrics for each LASSO model
    plot(lasso_model_data)
    
    ```   
```{r}
# Identify which tuning parameter (ie. lambda) is "best" 
lasso_model_data$bestTune
```   


```{r }
lasso_model_data$resample%>%
  summarize(mean(MAE))
```



```{r}
lasso_model_data$results
```




